spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: localhost:3306
    username: devdojo
    password: devdojo

logging:
  level:
    academy.devdojo: debug
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20
